package network.nishi.interiorextensions;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo {
    public static void loadInfo(ModMetadata meta) {
        meta.modId = InteriorExtension.MODID;
        meta.name = InteriorExtension.MODNAME;
        meta.description ="This mod add some interior block.";
        meta.version =InteriorExtension.VERSION ;
        meta.url = "https://github.com/nishi4321/Minecraft-InteriorExtensionsMod";
        meta.authorList.add("Nishi1234");
        meta.credits = "";
        meta.logoFile ="";
        meta.autogenerated = false;
    }
}
